### ISSUE TITLE
Local M2 port in use

### ISSUE THREAD

**Issue by coneill-math** [coneill-math/m2r#133]
We should check port availability before launching the process.

**Comment by dkahle** [comment]
Very nice, Chris!  Two things:

1. Can we safely remove the port warning? It makes loading __m2r__ look kinda nasty, especially in papers when I already have a process running :).  Second thought: you may want to increment only if the user is _not_ supplying a specific port; that would get you around the incrementing altogether (you won't message at all when incrementing, because presumably the user won't care).  The function `missing()`, when used in the body of a function, checks if the user supplied the argument.  

2. @sommars, can you try this on your Ubuntu box? I thought `netstat` was a MacOS thing, with `ss` being a rough *nix equivalent...

**Comment by coneill-math** [comment]
Just made both changes for item 1.

Jeff, let me know if item 2 comes up a bust, and (ideally) a linux system involving ss and fgrep that detects port usage.

**Comment by sommars** [comment]
This is great, thanks for implementing this!

I'm not sure what the "right" way to test this is, so I'm testing by running the line
`netstat -an | grep .27436 | wc -l`
in the command line when m2r is and is not connected. This always returns zero for me, because the lines that we're searching for look like this in linux land:
`tcp        0      0 127.0.0.1:27436         127.0.0.1:40848         ESTABLISHED`

**Comment by coneill-math** [comment]
Try now :).

**Comment by sommars** [comment]
Awesome, works great.

**Comment by dkahle** [comment]
Great!  In general I think there are two easy ways to check: either two RStudio instances running __m2r__ or one running __m2r__ and, at the same time, compiling the paper.
