### ISSUE TITLE
Add metadata to integers and numerics

### ISSUE THREAD

**Issue by coneill-math** [coneill-math/m2r#146]
For consistency.

**Comment by coneill-math** [comment]
Also do this with complex numbers (see `m2_parse_function.m2_tocc()`).

**Comment by dkahle** [comment]
How hard is this?  I've noticed that if I type `class 5` in M2 I get that is an element of the ring ZZ (class = ZZ, type = class class = Ring).  For `5.5`, I get that it is an element of RR, InexactFieldFamily.

I think I have a feel for how to do this, but I'm going to reassign to you, Chris.  If that's a problem, let me know.  I do think that this would be helpful for the current project, since it's already implemented for matrices (for example).

**Comment by coneill-math** [comment]
Personally, I think we should do this for all values returned from `m2_parse()`, including (for instance) mpoly objects.  Thoughts?

**Comment by sommars** [comment]
Agreed, I like classing everything from `m2_parse()`. However, will it ever bite an R user to have an object that's classed differently than expected?

**Comment by dkahle** [comment]
I think that's a good idea, too.  I don't think it will create problems for R users.  Remember, most `m2` objects are just `NA`s with meta data.  M2 objects that have analogues in R generally replace that `NA` with the relevant data structure, but they also get the meta data.

**Comment by dkahle** [comment]
BTW, I think this is the kind of thing we need to do before CRAN/paper submission, because it will alter how basic objects are printed out.  For example, an integer will print as an integer of length 1 but also have a line saying that they're elements of a ring.  

Vectors of integers may be a design challenge: does Macaulay2 have a type/data structure for vectors, or does it only have lists?  If it's only got lists, then it gets kind of weird, because they'll get parsed into a `m2_list` whose elements are integers, elements of `ZZ`, as opposed to a vector of integers.

**Comment by dkahle** [comment]
Second BTW: while we're doing this, we may want to just go ahead and do the __gmp__ stuff...

**Comment by coneill-math** [comment]
@dkahle, that's right, attaching metadata to a return value doesn't affect the way it is interpreted, only the way it is printed.  At worst, it will just be ignored.  

I will try to get to this soon, as it does seem like a big thing (the last thing?) to add before CRAN (and paper) submission.

**Comment by coneill-math** [comment]
Just added `m2_structure()` around each of the "basic" returns from `m2_parse()`.  Now the following: 

```R
> m2_parse("123")
[1] 123
attr(,"class")
[1] "m2_integer" "m2"
```

Is this about what we were picturing?

**Comment by coneill-math** [comment]
Now printing looks better.  

```R
> m2_parse("123")
[1] 123
> str(m2_parse("123"))
Classes 'm2_integer', 'm2'  int 123
```

Closing unless something looks off.
